require version file
I couldn't check gem version in `pry`, so it's better to require it.

```
pry> require 'business_time'
true
pry> BusinessTime::VERSION
NameError: uninitialized constant BusinessTime::VERSION
```